"""Experiment retrieval skill stub."""

from src.data.models import ArmVariant, Experiment, ExperimentMemory, MetricsSummary


class RetrievalSkill:
    def run(self, objective: str, experiment_id: str) -> dict:
        experiment = Experiment(
            experiment_id=experiment_id,
            objective=objective,
            status="completed",
            traffic_split={"control": 0.5, "variant_a": 0.5},
            owner="mvp",
        )

        arm = ArmVariant(
            experiment_id=experiment_id,
            arm_id="control",
            treatment_description="Current baseline treatment",
            structured_parameters_json={"ux_flow": "v1"},
            treatment_type="baseline",
            constraints_tag="default",
        )

        memory = ExperimentMemory(
            experiment_id=experiment_id,
            summary_text="Placeholder memory summary.",
            lessons_learned=["Need stronger context features for segmentation."],
            winning_patterns=[],
            failed_patterns=[],
            analyst_notes="Generated by retrieval stub.",
        )

        metrics = [
            MetricsSummary(
                experiment_id=experiment_id,
                arm_id="control",
                sample_size=1200,
                conversion=0.13,
                retention=0.4,
                engagement=5.1,
                revenue_proxy=2.0,
                variance=0.02,
                confidence_interval=[0.11, 0.15],
            )
        ]

        return {
            "experiment": experiment,
            "arms": [arm],
            "memory": memory,
            "metrics": metrics,
        }
