"""Experiment retrieval: benchmark parquets when available, else MVP stub."""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from src.data.models import ArmVariant, Experiment, ExperimentMemory, MetricsSummary
from src.retrieval.benchmark_context import load_context_from_benchmark, resolve_benchmark_dir


class RetrievalSkill:
    def __init__(self, benchmark_dir: Optional[str | Path] = None) -> None:
        self._benchmark_dir = benchmark_dir

    def run(self, objective: str, experiment_id: str) -> dict:
        benchmark_dir = resolve_benchmark_dir(self._benchmark_dir)
        loaded = load_context_from_benchmark(
            benchmark_dir=benchmark_dir,
            experiment_id=experiment_id,
            objective=objective,
        )
        if loaded is not None:
            return loaded
        return self._stub_context(objective=objective, experiment_id=experiment_id)

    def _stub_context(self, objective: str, experiment_id: str) -> dict:
        experiment = Experiment(
            experiment_id=experiment_id,
            objective=objective,
            status="completed",
            traffic_split={"control": 0.5, "variant_a": 0.5},
            owner="mvp",
        )
        arms = [
            ArmVariant(
                experiment_id=experiment_id,
                arm_id="control",
                treatment_description="Current baseline treatment",
                structured_parameters_json={"ux_flow": "v1"},
                treatment_type="baseline",
                constraints_tag="default",
            ),
            ArmVariant(
                experiment_id=experiment_id,
                arm_id="variant_a",
                treatment_description="Variant treatment bundle",
                structured_parameters_json={"ux_flow": "v2", "reward_rate": 1.1},
                treatment_type="configured_bundle",
                constraints_tag="default",
            ),
        ]
        memory = ExperimentMemory(
            experiment_id=experiment_id,
            summary_text="Placeholder memory summary.",
            lessons_learned=["Need stronger context features for segmentation."],
            winning_patterns=[],
            failed_patterns=[],
            analyst_notes="Generated by retrieval stub (no benchmark parquets found).",
        )
        metrics = [
            MetricsSummary(
                experiment_id=experiment_id,
                arm_id="control",
                sample_size=1200,
                conversion=0.13,
                retention=0.4,
                engagement=5.1,
                revenue_proxy=2.0,
                variance=0.02,
                confidence_interval=[0.38, 0.42],
            ),
            MetricsSummary(
                experiment_id=experiment_id,
                arm_id="variant_a",
                sample_size=1200,
                conversion=0.14,
                retention=0.48,
                engagement=5.4,
                revenue_proxy=2.1,
                variance=0.02,
                confidence_interval=[0.46, 0.50],
            ),
        ]
        return {
            "experiment": experiment,
            "arms": arms,
            "metrics": metrics,
            "memory": memory,
            "data_source": "stub",
        }
